### ISSUE TITLE
Peer's project review

### ISSUE THREAD

**Issue by faresdhane** [CIEE-Living-Data-Project/PREE_SophiaKast#2]

**Comment by faresdhane** [comment]
The description is clear and concise. The data folder contains two “_README” files, maybe you should keep only one or change the name of the other one (the done that do not describe your data). Script documents are well named and commented (I can easily follow the step to reproduce the output).
In conclusion, this project is reproducible and well explained, my only concern is with the REAME files where there are always two versions (in data and script folders).
Grade: 18/20

**Comment by sckast** [comment]
Thanks Fares! I noticed that, too, about the READMEs. It seemed like RStudio was auto-generating the .html versions?? I wasn't sure why. I'll delete the html ones and keep the Markdown ones.
